package com.finance.dashboard.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.servers.Server;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class SwaggerConfig {

    @Bean
    public OpenAPI customOpenAPI() {
        // Enforcing the base URL to uniquely be the relative root.
        // This permanently patches the HTTPS to HTTP Mixed Content blockers
        // generated by proxy hosts like Render or Heroku.
        return new OpenAPI().addServersItem(new Server().url("/"));
    }
}
